#!/bin/bash

# Interpret given arguments
ignore_logs=0
while test $# -gt 0; do
    case "$1" in
        -h|--help)
            echo "Usage: $0 [OPTIONS]"
            echo "Options:"
            echo -e "\t-i|--ignore-logs\tignore existing log files"
            echo -e "\t-h|--help\t\tdisplay this help and exit"
            exit 0
            ;;
        -i|--ignore-logs)
            echo "Will overwrite existing logs."
            ignore_logs=1
            shift
            ;;
        *)
            echo "$0: invalid option '$1'"
            echo "Try '$0 --help' for more information."
            exit 0
            ;;
    esac
done

# Compile and run all solutions that do not already have a log file.
# Write their execution time to main.log
ids=`find -name main.hs | grep -o "[0-9]\+" | sort -n`
for id in $ids; do

    if [ $ignore_logs == 0 ]; then
        find $id/main.log 2>/dev/null >/dev/null
        if [ $? == 0 ]; then
            echo -e "Problem $id already has a log."
            continue
        fi
    fi

    echo Compiling $id.
    ghc --make -O3 $id/main

    timeTmp=`mktemp`
    outputTmp=`mktemp`

    echo Running $id.
    find $id/input &> /dev/null
    if [ $? == 0 ]; then
        $( { time cat $id/input | $id/main; } 2>$timeTmp 1>$outputTmp )
    else
        $( { time $id/main; } 2>$timeTmp 1>$outputTmp )
    fi

    t=`cat $timeTmp | head -n 2 | tail -n 1 | cut -c 5-`
    o=`cat $outputTmp | tail -n 1`

    echo "Output is $o"

    echo $t > $id/main.log
    echo $o >> $id/main.log

    echo
done

# Generate README.md
# Create an entry for each problem that has a log file.
echo "Problem | Execution time | Answer" > README.md
echo ":-------|:--------------:|:------" >> README.md

totalSeconds=0
withLogs=`find -name main.log | grep -o "[0-9]\+" | sort -n`
entries=`echo $withLogs | tr ' ' '\n' | wc -l`

for id in $withLogs; do
    t=`cat $id/main.log | head -n 1`
    o=`cat $id/main.log | tail -n 1`

    if [ `echo $t | grep -v '^0'` ]; then
        t="**$t**"
    fi

    echo "$id | $t | $o" >> README.md

    minutes=`echo $t | sed 's/m.\+//g'`
    seconds=`echo $t | sed 's/.\+m\(.\+\)s/\1/g'`
    totalSeconds=`echo "$totalSeconds + $minutes * 60 + $seconds" | bc -l`
done

averageSeconds=`echo "$totalSeconds / $entries" | bc -l`
printf "Average | %.3fs\n" $averageSeconds >> README.md
